### ISSUE TITLE
fatal error: librdkafka/rdkafka.h: No such file or directory

### ISSUE THREAD

**Issue by fermelone** [TendTo/Dotingestion2#1]
Hi!

How are you managing the fact that confluent-kafka's wheel does not include an install of librdkafka?

Is that necessary for the build? or is it just for the dev environment? currently, this is preventing the `docker-compose up` command from running successfully.

Error: _(during ingestion's dockerfile pip install requirements):_
`confluent_kafka.h:23:10: fatal error: librdkafka/rdkafka.h: No such file or directory`

**Comment by fermelone** [comment]
Found that building the lib as a step in the ingestion dockerfile fixes the issues:

> RUN git clone https://github.com/edenhill/librdkafka.git
WORKDIR /app/librdkafka
RUN /app/librdkafka/configure --prefix /usr
RUN make
RUN make install

**Comment by fermelone** [comment]
Complete ingestion Dockerfile looks like this:

> FROM python:3
> ENV PATH /usr/src/app/bin:$PATH
> WORKDIR /app
> 
> RUN git clone https://github.com/edenhill/librdkafka.git
> WORKDIR /app/librdkafka
> RUN /app/librdkafka/configure --prefix /usr
> RUN make
> RUN make install
> 
> WORKDIR /app
> 
> COPY requirements.txt .
> RUN pip3 install -r requirements.txt
> 
> COPY . .
> 
> ENTRYPOINT [ "python3", "app.py" ]

**Comment by TendTo** [comment]
I never noticed this issue, because the last time I checked the docker container was using Python 3.9.6. The current one uses Python 3.10, and there seems to be some kind of incompatibility. Maybe the container itself is lacking some libraries, or the version of confluent-kafka I'm using is not exactly compatible.
To be safe, I will specify the Python version 3.9 in the Dockerfile, since it seems to start the container correctly,  but I do appreciate your effort and your solution, for it could benefit someone who has encoutered the same issue, expecially if they want to use the lastest features.
